baseurl = "https://www.moonstreet.nl"
title = "moonstreet.nl"
author = "Moonstreet"
copyright = "Copyright © 2019, Moonstreet, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Moonstreet Weblog"
introDescription = "A weblog about cyber security and devops stuff"
contentSharing = ""


